---
title: "Exploratory overview of Berlin city trees"
author:
  - Alexander Hurley:
      email: hurley@gfz-potsdam.de
      institute: [GFZ]
      correspondence: true
  - Ingo Heinrich:
      email: heinrich@gfz-potsdam.de
      institute: [GFZ]
      correspondence: false
institute:
  - GFZ: Geoforschungszentrum Potsdam
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
    bookdown::html_document2:
      fig_caption: yes

bibliography: references.bib
csl: "../templates/journal-of-archaeological-science.csl" # Insert path for the bib-style
abstract: |
  Quick overview of publicly available tree records.
keywords: |
  Uferbaeume; Anlagenbaeume; Strassenhighlights
highlights: |
  We will see. 
---


<!--     bookdown::word_document2: -->
<!--       fig_caption: yes -->
<!--       reference_docx: "../templates/template.docx" # Insert path for the DOCX file -->
<!--       pandoc_args: -->
<!--       - --lua-filter=../templates/scholarly-metadata.lua -->
<!--       - --lua-filter=../templates/author-info-blocks.lua -->
<!--       - --lua-filter=../templates/pagebreak.lua -->


<!-- This is the format for text comments that will be ignored during renderings. Do not put R code in these comments because it will not be ignored. -->

```{r setup, echo = FALSE, cache = FALSE, include = FALSE}
knitr::opts_knit$set(root.dir = here::here())

knitr::opts_chunk$set(
  fig.align = "center",
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  comment = "#>",
  # fig.path = "../figures/",
  fig.path = paste0(file.path(here::here(), "analysis", "figures"), "/"),
  dpi = 300
)


library(drake)
library(ggplot2)
```

# Introduction

Here is a citation [@Marwick2017]

# Background

# Methods

# Results

Some results


```{r fig-tree-overview-map, fig.cap="A plot of random numbers",fig.width = 15, fig.height = 8, out.width="100%"}
readd(plot_overview_map)
# plot_overview_map

```


```{r fig-tree-count-map, fig.cap="A plot of random numbers",fig.width = 12, fig.height = 12, out.width="100%"}
readd(plot_count_map)
# plot_count_map

# plot(1:10)
```


<!-- Figure \@ref(fig:demo-plot) shows how we can have a caption and cross-reference for a plot -->

# Discussion

# Conclusion

# Acknowledgements

<!-- The following line inserts a page break  -->
\newpage

# References 
<!-- The following line ensures the references appear here for the MS Word or HTML output files, rather than right at the end of the document (this will not work for PDF files):  -->
<div id="refs"></div>

\newpage

### Colophon

This report was generated on `r Sys.time()` using the following computational environment and dependencies: 

```{r colophon, cache = FALSE}
# which R packages and versions?
if ("devtools" %in% installed.packages()) devtools::session_info()
```

The current Git commit details are:

```{r}
# what commit is this file at? 
if ("git2r" %in% installed.packages() & git2r::in_repository(path = ".")) git2r::repository(here::here())  
```
